# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WA6Sks1IydNXNITLq53F90qjYt8SIEbU
"""

import random

# aleatorio =  random.choises(10000,20000)
# meu_chute = int(input('Digite seu chute: '))

# #condição verdadeira
# if meu_chute == aleatorio:
#    print(aleatorio + meu_chute)
#    print('Show de bola!', aleatorio)
# # codição falsa
# elif meu_chute >= aleatorio:
#    print('esta quase acertando', aleatorio)

# else:
#     print('Errou feio', aleatorio)

# random.random
# random.randint
# random.randrange



# DESAFIO

#SISTEMA DE SENHAS
# 1 - O COMPUTADOR CRIA UMA SENHA ALEATORIA
# 2 -  VC DIGITAR SENHA DE ACESSO
# 3 -  VERIFICAR SE O UUSARIO PODE ACESSAR O SISTEMA



senha_pc = random.randrange(10000,10001)
minha_senha = int(input(':'))

if senha_pc == minha_senha:
    print('Acesso permitido')
else:
    print('Acesso negado')

